@Url = http://localhost:5050/api/contacts

GET {{Url}}

###

GET {{Url}}?limit=2&page=3&sort=full_name:desc

###

GET {{Url}}/e61bc045-f55b-4390-ac22-cb83734561ed

###

POST {{Url}}
Content-Type: application/json

[
    { 
        "FullName": "Alemayehu Zegeye", "Email": "alex@mail.co.uk", 
        "Phone": "+11-458-6300", "Address": "Cambridge, UK" 
    }
]


###

DELETE {{Url}}/f72a0786-d911-40fd-8b75-bf2be3ba4df6

###

DELETE {{Url}}/49b670d4-1e1e-4202-81af-f995e723d4f6,68554c9a-a62d-4998-a789-3deaa7092249"]

###

PUT {{Url}}
Content-Type: application/json

[
    {
        "FullName": "Abebech Tadesse",
        "PublicId": "e61bc045-f55b-4390-ac22-cb83734561ed",
        "Email": "abe@mail.co.uk",
        "Phone": "+11-985-9632",
        "Address": "London, UK"
    }
]